### ISSUE TITLE
Syntax highlighting and checking inline python expressions

### ISSUE THREAD

**Issue by xylix** [robocorp/robotframework-lsp#129]
**Is your feature request related to a problem? Please describe.**
Inline python, including KWs such as evaluate, Run Keyword If and the `${{}}` syntax is sometimes difficult to read and debug.

**Describe the solution you'd like**
 Would be useful if the LSP could provide syntax support for the cases where its easily detectable. This could perhaps work using an existing python lsp for checking the sections of Robot syntax that have python in them.

**Describe alternatives you've considered**
I guess the biggest alternative is just to not implement this. AFAIK no other robot tool provides support like this.

**Comment by fabioz** [comment]
Hi @xylix I agree it sounds something nice to have, still, I'm closing this issue for now to shorten the the backlog.

Note: I'm marking things that may be done later with the maybe later tag so that it's searchable in the future (so, this is closed as there are no plans to tackle it in the short/mid term -- it can be reopened if someone provides a pull request or if higher priority items are no longer available).
