### ISSUE TITLE
Launch a separate process to load robotframework

### ISSUE THREAD

**Issue by fabioz** [robocorp/robotframework-lsp#14]
The benefits here are:
- The extension can use a python version independent from the `robotframework` version (so, we don't need to support older versions of Python).
- Operations taking time on `robotframework` don't halt the extension.

**Comment by bollwyvl** [comment]
Over on `pygls`, they have some [nice features](https://pygls.readthedocs.io/en/latest/pages/tutorial.html#blocking-command-test) for doing just such a thing.

`pygls` _also_ implements the virtual file system stuff pretty robustly: `pyls` on the other hand (partially due to `rope`, etc) requires files actually exist on disk for a number of features to work, which prompted us to do some [pretty crazy things](https://github.com/krassowski/jupyterlab-lsp/blob/master/py_src/jupyter_lsp/virtual_documents_shadow.py) on `jupyter_lsp`. stock `robotframework` also expects real files, too... unless you've got some of @datakurre's kit from [robotkernel](https://github.com/robots-from-jupyter/robotkernel/blob/c91d40a416199e036b1ba64fbcc750b5637caf78/src/robotkernel/builders_32.py#L43)...

**Comment by datakurre** [comment]
@bollwyvl 

> stock robotframework also expects real files, too... unless you've got some of @datakurre's kit from robotkernel...

That was `robotframework < 3.2`. `robotframework >= 3.2` (still in beta) has the new parser discussed at the robocon, which you particiated! It has public API for parsing even from strings, and it also has public API to parse into `ast`, to make projects like `robotframework-lsp` sane to implement.

**Comment by fabioz** [comment]
Note that the current version of the language server is already doing analysis without a file on disk using the in-memory generated ast as @datakurre mentioned (even though the initial implementation is based on `pyls` and not `pygls`, support for in-memory buffers is there).

-- I'll take a look at `pygls` to see what we could gain from it... I'm not sure about it because we'll use the same code to communicate with the separate shell, so, at least that part of the code also needs to support Python 2.7 as long as `robotframework` also supports it and `pygls` is Python 3.5+ only).
