### ISSUE TITLE
Configuring and running linter tool together with LSP

### ISSUE THREAD

**Issue by bhirsz** [robocorp/robotframework-lsp#152]
Visual Studio Code and some other IDEs have built in support for linter tools like pylint, pep8 etc that can be configured and run on file save.

It would be awesome to have this with Robot Framework plugin. I'm coauthor of [Robocop](https://github.com/MarketSquare/robotframework-robocop)  which can be used to scan robot files. I have general idea where we could put this. According to documentation from Microsoft for LSP server we can use [Diagnostic](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#diagnostic ). RF LSP have  basic implemention of it under [Url](https://github.com/robocorp/robotframework-lsp/blob/ed8080a62b4d5933423327e83d08fddf6cdb2092/robotframework-ls/src/robotframework_ls/impl/code_analysis.py#L104)  but it does only cover missing keywords.

What we need in short? To be able to configure and start our application in LSP startup and then call it with something like scan_file(path) everytime we need analysis. Of course I need to update Robocop to be able to run it continously like that and to return analysis results in format suitable for LSP.

I could also try to raise PR here but it would be good to discuss proposed architecture first.

**Comment by fabioz** [comment]
It seems nice... 

Now, on how to integrate:

1. There should be a property to enable linting (probably something as `robot.lint.robocop.enabled` to enable and then if it works with arguments something as `robot.lint.robocop.args` -- or the integration could say the actual things to be customized (if any) -- something as: `robot.lint.robocopy.showWarnings` or `robot.lint.robocopy.silenceMessages.`

- That goes in: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/package.json#L44

2. For calling the linter I see 2 options: 

- Use as a command line (ideally here the linter also accept receiving something as `-` as a parameter and then read the contents from the stdin (so that it could work without having to save the contents to a file to be able to do the analysis).

- Use some api directly... I see that it's implemented as mostly visitors over the robot framework ast, which the language server already gets for its own code analysis (in: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/src/robotframework_ls/impl/code_analysis.py#L114), so, if there's some API to just collect errors from the ast that could be even easier to integrate and wouldn't require calling a separate executable (it'd just be called from that same code in `collect_analysis_errors`, possibly converting the error from the linter format to what's expected in the language server), although if the linter is slow having it as a separate executable may be better.

A note: I think it probably makes sense to always silence errors which are already collected by the `Robot Framework Language Server` (such as syntax errors) by default.

**Comment by bhirsz** [comment]
1. I was thinking about enabled True/False and args at start. We will also support auto loading configuration files (like ".robocop") on top of CLI so configuring is easy. LSP of course would need to inject extra own arguments, like ignoring errors already detected by LSP.
Thanks for pointing to place with configuration

2. Right now we only support loading from files (it opens the file, get its model and then runs it through checkers - using ast trees). The second option is most appealing - but we still would need to pass whole file model as some of the rules need to parse it whole (for example duplications rules). Linter is quite fast and results are instanteous but it's hard to predict how it will change after extending our rule base. 
I will try update Robocop to have some general public api so it could be used programmatically, not through CLI, and implement basic solution with collect_analysis_errors. I will update results in this issue.

To note - we also raise syntax errors but we can easily ignore them in Robocp so that's fine.

**Comment by bhirsz** [comment]
On second though collect_analsys_errors runs on code completion (correct me if I'm wrong). That's why ast you have here is the ast around modified code. It would be probably easier at start to run linter checks on file save. I will investigate both options

**Comment by fabioz** [comment]
No, `collect_analysis_errors` receives a `completion_context`, but that's just an abstraction for the `editor text/text selection/ast/workspace` contents in memory (it doesn't run on code completion -- those are in 2 actually distinct processes: there is a dedicated process just for code-analysis and another process for code completion/formatting/etc).

Note that the `completion_context` has the ast in `completion_context.get_ast()` as well as the actual source contents in `completion_context.doc.source`, the path in `completion_context.doc.path` and the config in `completion_context.config` (see the protocol in https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/src/robotframework_ls/impl/protocols.py#L146).

If it should work on the command line I think the linter should be modified to accept `-` as the input (that's pretty standard for many tools -- as an example you can see how the `black` formatter does it: https://github.com/psf/black/blob/6dddbd72414061cde9dd8ee72eac373b7fcf8b54/src/black/__init__.py#L674). If you also need the filename in this case it should be passed as an argument.

**Comment by bhirsz** [comment]
Thanks for detailed explanation! 

Good idea. It's bit tricky to implement with our current solution but I will definitely consider it - I'm going to need it anyway if I want to avoid issues with opening the same file by two processes (linter/IDE) or supporting parallel execution

**Comment by fabioz** [comment]
Humm, I think it should be straightforward as RF already supports creating the AST in-memory (so, let me know if you need any help there as I can point you to the right direction).

i.e.: it doesn't seem it should be difficult to receive `-` and a `--file` parameter and return an `InMemoryContentsWithPath` object in `https://github.com/MarketSquare/robotframework-robocop/blob/43ce30905df80db4616782b0267420488b723f70/robocop/run.py#L161` (it'd may need some instance checks later on, but looking at the code it seemed straightforward).

**Comment by fabioz** [comment]
I'm closing and marking this as `maybe later` as I won't be getting this myself in the mid-short term (still, feel free to create a pull request and I'll review it or comment more on the issue itself... i.e.: only the issues that I have a plan to tackle in the mid-short term with a higher priority are kept in the `open` state).
