### ISSUE TITLE
LSP 0.6.0: No rpaframework keywords found when using rpaframework greater than 6.4.*

### ISSUE THREAD

**Issue by janipalsamaki** [robocorp/robotframework-lsp#199]
LSP 0.6.0 (VS Code) complains about missing keywords when using `rpaframework` greater than `6.4.*`  (so `6.5.*`, `6.6.*`, `6.7.*`).

- Built-in keywords are found (only `rpaframework` seems to be affected).
- Running the robot works (only LSP seems to be affected).

Can be replicated with this simple robot, where `Absolute Path` is either found or not based on the `rpaframework` version. This affects possibly other `rpaframework` libraries, too:

```robot
*** Settings ***
Library           RPA.FileSystem

*** Tasks ***
File system operations
    ${absolute_path}=    Absolute Path    ${CURDIR}
```

> This is potentially an issue with `rpaframework` itself, but since it only seems to affect LSP, posting here.

**Comment by fabioz** [comment]
Ok, so, when installing rpaframework 6.5, the error I see when trying to create the .libspec is:

```
subprocess.CalledProcessError: Command '['C:\\Users\\fabio\\AppData\\Local\\robocorp\\live\\4fc012d7304dd721e23630c390ed065b83e63788e40bf008adf943044ebabc1a519b56\\python.exe', '-m', 'robot.libdoc', '--format', 'XML:HTML', '-P', 'x:\\vscode-robot\\local_test\\CheckEnvJson', '-P', 'x:\\vscode-robot\\local_test\\CheckEnvJson\\.', 'RPA.FileSystem', 'C:\\Users\\fabio\\.robotframework-ls\\specs\\8ad22d5a_3.2.2\\user\\RPA.FileSystem.libspec']' returned non-zero exit status 252.
lsp: 2020-11-28 10:46:37 UTC pid: 20084 - ThreadPoolExecutor-1_1 - EXCEPTION - robotframework_ls.impl.libspec_manager
Error creating libspec: RPA.FileSystem. Output:
reST format requires 'docutils' module to be installed.
```

Probably what happened is that `rpaframework` documentation format changed and now requires `docutils` to be generated.

So, after changing the robot `conda.yaml` to include `docutils` it seems to work for me:

```
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7.5
  - pip=20.1
  - pip:
    - rpaframework==6.5.*
    - docutils
```

I think the real fix would be having `docutils` as a dependency on either `rpaframework` or `robotframework` itself (since it can't generate the docs in this case unless `docutils` is installed).

**Comment by janipalsamaki** [comment]
Confirmed that adding `docutils` as a dependency solves this issue. Created an issue for `rpaframework`: https://github.com/robocorp/rpaframework/issues/88

This issue can be closed, I guess? :)

**Comment by osrjv** [comment]
@fabioz, as a small clarification we didn't change the docstring format, but we _did_ add missing `ROBOT_LIBRARY_DOC_FORMAT` attributes to reST-documented libraries, which obviously broke stuff.

I think RF will be reluctant to have it as a required dependency instead of optional, but we can ask. In any case, I think it'd better if LSP would either fallback to raw docstrings or have docutils as a required dependency.

**Comment by fabioz** [comment]
The main problem is that it's not possible to me to add that dependency on the LSP itself because the libspec must be generated using the environment that the user uses and not the environment that LSP uses to run (because otherwise not even `rpaframework` would be available).

Thinking about it a bit more, I think that this doesn't really match with RF itself (given that its docstrings don't really use the `reST` format itself) and the `docutils` dependency should be on `rpaframework` as it's the one that needs to have `docutils` installed to generate its documentation).

I can probably do the fallback to force the `--docformat` if that error is detected, but the documentation format will probably be worse for the user in that case.

**Comment by osrjv** [comment]
Alright, makes sense about environments. I can add docutils to rpaframework dependencies as a fix, but I want to make clear that the error comes from RF's libdoc and it advertises first-class support for reST docstrings. There will be other libraries with similar issues, and bad docstrings would probably be better than no autocomplete for them at all.

**Comment by fabioz** [comment]
Yeap, I'll add the fallback anyways.

As for the dep being on RF itself, I'm still uncertain... it really does make sense to add that dep only for libraries that actually rely on reST (and thus, being only an optional dep for RF).
