### ISSUE TITLE
Robot Creation Error

### ISSUE THREAD

**Issue by megaten88** [robocorp/robotframework-lsp#200]
**Describe the bug**
Any action related with robot gets an error, either creation or just update the robot view. There is no documentation available on what the problem may be.

**To Reproduce**
1. Open VS Code
2. Ctrl+Shift+P
3.- Select "Robocorp: Create Robot"

**Expected behavior**
I expected a template selection for the robot creation.

** Result **
Error appears as: Command 'Robocorp: Create Robot' resulted in an error (command 'robocorp.createRobot' not found)

**Screenshots**
![roboterror](https://user-images.githubusercontent.com/19882474/100383245-cc33e700-2fe2-11eb-9684-1c46645ad4a8.png)

**Versions:**
 - OS: Windows 10
 - Robot Framework Version: 3.2.2
 - Robot Framework Language Server Version: 0.6.0
 - Client Version: VSCode 1.51.1

**Comment by fabioz** [comment]
This usually means that there was some error activating the extension.

Do you have something under the `OUTPUT > Robocorp Code` tab?

i.e.:

![image](https://user-images.githubusercontent.com/117621/100383668-ec709f80-2ffc-11eb-8bde-7a6cf2a46297.png)

**Comment by megaten88** [comment]
Yes, I do have the following output: 
![image](https://user-images.githubusercontent.com/19882474/100384066-e1aa1080-2fe4-11eb-87ab-563e77ab9850.png)

**Comment by fabioz** [comment]
It seems this is actually an issue with `rcc` (which is the tool that automatically creates a conda environment with the python dependencies to bootstrap the language server).

I created an issue to track it at the related repo: https://github.com/robocorp/rcc/issues/4 (I'll keep this one open until that one is also fixed and a release is done with it).

**Comment by megaten88** [comment]
Okay, thank you very much.

**Comment by fabioz** [comment]
@megaten88 it seems this happens because `conda` itself doesn't support having spaces in its environments (and the default place for the environments is under your username folder which has spaces).

The current workaround for that is setting the `ROBOCORP_HOME` environment variable to a place without spaces in its path.

To do that you can do something as:

```
setx ROBOCORP_HOME c:\robocorp
```

-- `setx` sets the environment variable in the windows registry, so, it should persist among Windows restarts.

Note that you have to restart code afterwards (and if you launch it from a shell, you also have to restart the shell).

**Comment by fabioz** [comment]
A new version was released with a fix that detects such a situation and asks for a new home path which doesn't contain spaces and saves that in the settings in `robocorp.home` (this may be changed if later on conda supports spaces).

This is fixed in `Robocorp Code 0.5.1`. If you're doing RobotFramework Robots, `Robot Framework Language Server 0.6.1` is also required.

**Comment by gjimenexv** [comment]
I'm using Robot Framework Language Server v0.7.0 and Robocorp Code v0.6.2.
Then I tried to run > Robocorp: Create Robot so I got the same error.

How can the issue with Conda be solve?

**Comment by fabioz** [comment]
@gjimenexv this issue is solved, but you may have a different issue with the same symptoms.

Given that, please open a new issue and include the contents of `OUTPUT > Robocorp Code` (as in: https://github.com/robocorp/robotframework-lsp/issues/200#issuecomment-734437785).
