### ISSUE TITLE
Add RobotFramework library arguments support

### ISSUE THREAD

**Issue by mrdimfox** [robocorp/robotframework-lsp#265]
**Problem description.**
For now, `robocorp.robotframework-lsp-0.9.1` falls with error

```python
Error creating libspec: SomeLibrary.
Return code: 252
Output:
Library 'SomeLibrary' expected 2 to 3 arguments, got 0.
```
if any count of args required for a user RobotFramework library.

**Possible solution**
Probably `robotframework-lsp` could detect a types of arguments using typehints and use this info to generate lib specs with the correct libdoc call. If it's not possible then some kind of configuration option could be provided in `setting.json` to match lib name and default arguments. Or it could be any other special description file in the workspace.

**Comment by fabioz** [comment]
Automatically guessing arguments is something pretty hard to do in practice... The recommended solution is for libraries to have default arguments so that libspec generation can work or you can pre-generate the `.libspec` files manually and place it in the workspace.

I guess having a configuration in the settings could also be a possibility, but I'm not sure about it... in practice for libraries you control usually just having default arguments is much more straightforward and for others the manual generation also suffices.

**Comment by mrdimfox** [comment]
Ok, I got u.

But if I have a library as a python package, how could I pre-generate libspec for it? I have already had some pre-generated docs inside lib packages. But they are in `xml` format and are located not in the root package folder. Should I re-regenerate specs in my current workspace folder? How LSP going to find it?

**Comment by fabioz** [comment]
The usual command line would be:

`python -m robot.libdoc --format XML:HTML <library_name> <library_name.libspec>`

As you have custom usage for the parameters, you may want to take a look at: 
`python -m robot.libdoc -h`
to see how to tackle that.

You can just place the `.libspec` under a file anywhere in the workspace or directly under some entry in the PYTHONPATH and the language server should find it.

**Comment by mrdimfox** [comment]
Cool! Thank you. I'll try it.

**Comment by fabioz** [comment]
Great that it works for you... Closing issue ;)
