### ISSUE TITLE
LSP library search path does not match Robot Framework

### ISSUE THREAD

**Issue by osrjv** [robocorp/robotframework-lsp#266]
**Describe the bug**
Robot Framework searches relative library imports based on `sys.path` as a fallback. LSP only searches relative to the working directory. As a result, certain imports work while running robots, but fail when creating libspec for LSP.

RF implementation visible here: https://github.com/robotframework/robotframework/blob/f45747dfec1095359379ba0088cecd955a83e576/src/robot/utils/robotpath.py#L157

Originally reported on forums: https://forum.robocorp.com/t/vscode-new-create-robot-project-cant-find-python-keywords/589

**To Reproduce**
1. Create Extended template with Robocorp Lab (or rcc), try to open `tasks.robot` with LSP

or
1. Create the following structure:
```
libraries/Library.py
tasks.robot
```
2. Add `libraries` to `PYTHONPATH`
3. In `tasks.robot` write:
```

*** Settings ***
Library     Library.py
```

**Expected behavior**
Not sure. This functionality of RF doesn't seem to be documented anywhere and works differently than I expected. It _is_ however a difference, so decided to document it here as an issue.

**Versions:**
 - Robot Framework Version: 3.2
 - Robot Framework Language Server Version: 0.9.1

**Logs**
See attached forum post

**Comment by pekkaklarck** [comment]
It's true that Robot Framework tries to find imports like `Library.py` from directories in PYTHONPATH. The reason is that it uses the exact same code for finding libraries using a physical path, not name, that is uses to find resource files. This is kind of an accident and I would highly recommend importing libraries by name like `Library` if they are in PYTHONPATH. Since RF works that way, and there are no plans to remove this support, I guess LSP should support it as well. I just wouldn't consider it too high priority.
