### ISSUE TITLE
Question: how to get auto-completion for third party libraries?

### ISSUE THREAD

**Issue by wlad** [robocorp/robotframework-lsp#277]
Seems I get auto-completion for Robot Framework's buildin and standard libraries only.
![image](https://user-images.githubusercontent.com/64201310/112393091-c59c4e80-8cfa-11eb-86f0-5898f722e380.png)

How to get auto-completion for all libraries installed inside a venv, i.e.

```
$ which python
/home/wlad/.venvs/num-e2e/bin/python

$ pip list
...
RESTinstance                 1.0.0
robotframework               4.0
robotframework-browser       3.1.0
robotframework-jsonlibrary   0.3.1
...
```

**Comment by fabioz** [comment]
It should work out of the box when the library is available (as long as its `.libspec` can be generated).

See: the faq: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-proceed-if-keywords-from-a-library-are-not-being-resolved for some common issues.

Also note that Robot Framework itself has an issue dealing with library names ending with `.json` due to https://github.com/robotframework/robotframework/issues/3919  (see: https://github.com/robocorp/robotframework-lsp/issues/294#issuecomment-813334158 for a workaround if that's your use-case).

Please reopen with the logs mentioned in the `faq` if you're not able to solve it with those instructions.
