### ISSUE TITLE
Local Python Libraries are not recognized

### ISSUE THREAD

**Issue by mnojek** [robocorp/robotframework-lsp#287]
Importing local libraries in Robot Framework (In PyCharm) like:
```
Library    my_lib.py
```
does not work - functions are not recognized as keywords and are underscored with red. Also it's not possible to quickly go to the declaration of Library even if the path is correct.

**Comment by fabioz** [comment]
Please take a look at the related FAQ: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-proceed-if-keywords-from-a-library-are-not-being-resolved

If you still cannot fix it with that, please provide the logs so that I can take a look at what's happening in your particular case.

**Comment by mnojek** [comment]
It works. Thanks!
