### ISSUE TITLE
Keywords under Run Keywords are not recognized

### ISSUE THREAD

**Issue by mnojek** [robocorp/robotframework-lsp#291]
Keywords provided as arguments for `Run Keywords` are not recognized as keywords, thus do not support 'go to declaration' feature. I'm using PyCharm 2020.3.5 with RFLS plugin v0.11.1.

**Comment by fabioz** [comment]
Note: same thing for `Run Keyword`.

**Comment by HaaiHenkie** [comment]
The same is true for all Builtin keywords that run other keywords. Autocomplete and highlighting is also not supported for keywords that are used as argument.

```RobotFramework
*** Settings ***
Suite Teardown    Suite Teardown
Test Teardown     Test Teardown

*** Test Cases ***
Keywords running other keywords
    Repeat Keyword    5 times    No Operation
    Run Keyword    No Operation
    Run Keyword And Continue On Failure    No Operation
    Run Keyword And Expect Error    Error    Fail    Error
    Run Keyword And Ignore Error    Fail    Error
    Normal Return
    Conditional Return
    Run Keyword And Return Status    No Operation
    Run Keyword And Warn On Failure    No Operation
    Run Keyword If    ${true}    No Operation
    Run Keyword If    ${true}    No Operation
    ...    ELSE IF    ${true}    Sleep    4s
    ...    ELSE    Fail
    Run Keyword Unless    ${false}    No Operation
    Run Keywords    Sleep    4s
    ...    AND    No Operation
    Wait Until Keyword Succeeds    5s    1s    Sleep    4s

*** Keywords ***
Suite Teardown
    Run Keyword If All Tests Passed    No Operation
    Run Keyword If Any Tests Failed    No Operation

Test Teardown
    Run Keyword If Test Failed    No Operation
    Run Keyword If Test Passed    No Operation
    Run Keyword If Timeout Occurred    No Operation

Normal Return
    Run Keyword And Return    No Operation

Conditional Return
    Run Keyword And Return If    ${true}    No Operation
```

**Comment by Hristovski** [comment]
Using the latest **PyCharm 2021.1.3** with **Robot Framework Language Support 0.18.0** is the same.
And I just wanted to also add **Run Keyword And Return Status** to the affected keywords.

**Comment by xylix** [comment]
This is of course partially thanks to the type of the upstream objects inputs' being `str` and `*args` instead of the corresponding Keword or function.

https://github.com/robotframework/robotframework/blob/b68e2b689515446056e53edd67bc23c4c1fd8be0/src/robot/libraries/BuiltIn.py#L1856

In general properly typing Robot Framework's higher order keywords would be quite interesting. And perhaps would also enable auto completion and validation for them when using python LSP when programming Robot.

But fixing it upstream is probably out of scope for Robot LSP. Most likely there are way easier ways to just figure out completion for them keyword-by-keyword for example. Perhaps by using the metadata from the `@run_keyword_variant` decorator that most such methods have. But that feature is supposed to be deprecated at some point https://github.com/robotframework/robotframework/issues/2190.

**Comment by fabioz** [comment]
Most likely the initial fix for this would be a hard-coded list of keywords that are expected to receive other keywords.

Now, there are a number of features that could be affected by this (find definition, code-completion, code analysis, syntax highlighting...), so, probably, we'd do a 2nd step parsing converting those strings to an AST and later on adding that info to the existing AST or have some utility method which'd do that on-demand.

The RobotFramework AST doesn't have this structure right now, so, what needs investigation is how to actually add that info to the existing AST in a way that is as straightforward as possible to have the features we have to work with that enhanced AST with as little change as possible (ideally those wouldn't need to be changed, it'd be up to the step where we collect the AST information we're interested in to do the needed handling).

**Comment by pekkaklarck** [comment]
Yeah, the easiest solution to start with is a hard-coded list. There aren't that many keywords so creating such a list isn't a big problem. Then the UI could be added and for most parts everything would work fine.

A better solution is then somehow getting this information from RF itself. That should be done as part of the already mentioned robotframework/robotframework#2190. I'd _really_ like to get that issue fixed in general and its already in RF 5.0 scope. I'll add a note to the issue about exposing this information publicly so that LSP can use it as well.

**Comment by fabioz** [comment]
> I would assume that from LSP point of view it would be most convenient if parser could tokenize data so that keyword name in arguments would get KEYWORD type instead of ARGUMENT. The returned model could have a separate method for doing this tokenizing similarly as there's a method for tokenizing variables in token values.

I agree, if that was directly reflected in the AST, it'd be ideal.

**Comment by pekkaklarck** [comment]
Let's see what we can do. At least with custom libraries possibly using this functionality this would require first parsing the data, then importing libraries to see do they use this functionality, and after that tokenizing arguments again.

**Comment by fabioz** [comment]
I think that if it requires importing libraries this would be a -1 from the language server. If that's the case, it's better to just add the information to the libspec (where the libraries are imported anyways) and then the language server can use that information to do what it needs afterwards without having the info baked into the AST.

i.e.: Importing is full of problems and can be very slow, whereas parsing should always work and must be very fast.
