### ISSUE TITLE
Robocop flagging trailing line missing when one exists

### ISSUE THREAD

**Issue by mattg9** [robocorp/robotframework-lsp#292]
![bug](https://user-images.githubusercontent.com/8210277/113348866-2b916300-9305-11eb-92f2-0b54a7aae7f0.jpg)

**To Reproduce**
I have run robocop against my files in the past, one trailing line removes any warning
Pycharm warning is shown...but a trailing line does exist

**Expected behavior**
no robocop warning

**Screenshots**
attached

**Versions:**
 - OS: [e.g. Windows 10]
 - Robot Framework Version 4
 - Robot Framework Language Server Version 0.12.0
 - Pycharm

**Comment by fabioz** [comment]
This was a `Robocop` issue... it's actually already fixed in `Robocop` that's bundled in the `Robot Framework Language Server` version 0.12.0, but you probably also have `Robocop` installed (in which case you have to either remove it so that the bundled version is used or you need to install the latest version of `Robocop` from its `master` as the last release (1.6.1) still has this issue).
