### ISSUE TITLE
Keep a single newline? 

### ISSUE THREAD

**Issue by hellt** [robocorp/robotframework-lsp#315]
Hi and thanks for working on rf-lsp

I am using this LSP in VSCode and was wondering if it is the lang server/extension that removes any newlines I put between my keywords in a test case?

I.e. if I have

```robot
Verify links in bridge
    ${rc}    ${output} =    Run And Return Rc And Output
    ...    sudo ip link show ${br-link1-name}

    Log    ${output}
```

on format I will have the newline removed

```robot
Verify links in bridge
    ${rc}    ${output} =    Run And Return Rc And Output
    ...    sudo ip link show ${br-link1-name}
    Log    ${output}
```

**Comment by fabioz** [comment]
The language server mostly wraps the standard code formatter from `Robot Framework` itself (https://github.com/robotframework/robotframework/blob/master/doc/userguide/src/SupportingTools/Tidy.rst)

So, if you'd like to have something different, please report it to `Robot Framework` project itself, which provides the tool.

There are also plans to integrate a new tidy tool too (See: https://github.com/robocorp/robotframework-lsp/issues/273).

I'm also open to integrating other tidy-related tools into the language server, but creating or changing the behavior of the actual code formatting tools is out the scope of the language server (which is why I'm closing this issue).

**Comment by hellt** [comment]
Thank you,
I was not sure if that falls under LSP or elsewhere. You cleared the
confusion
