### ISSUE TITLE
Incompatible with PyCharm 2021.1

### ISSUE THREAD

**Issue by DmytroSokhach** [robocorp/robotframework-lsp#319]
**Describe the bug**

**To Reproduce**
Update PyCharm to 2021.1

**Expected behavior**
Starts and works

**Screenshots**
-

**Versions:**
 - OS: MacOS 10.15.7
 - Robot Framework Version: 4.0.1
 - Robot Framework Language Server Version: 0.14
 - Client Version: PyCharm 2021.1

**Logs**
Tried to obtain logs, but the manual is not trivial, spent 15 minutes - have no clue why logs are not written.

**PyCharm Error is:**
`Plugin 'Robot Framework Support' (version '0.24') is not compatible with the current version of the IDE, because it requires build 203.* or older but the current build is PC-211.6693.115`

**Comment by fabioz** [comment]
You're trying to install a different plugin. 

The plugin related to `robotframework-lsp` is `Robot Framework Language Server` 
-- i.e.: https://plugins.jetbrains.com/plugin/16086-robot-framework-language-server

So, if you try to install `Robot Framework Language Server` (instead of `Robot Framework Support`), it should work ;)
