### ISSUE TITLE
High CPU when Robot Framework Language is loaded in Pycharm

### ISSUE THREAD

**Issue by cookindutch** [robocorp/robotframework-lsp#350]
When I installed the Robot Framework Language in Pycharm the CPU usage went from 3% to 25% - 36% continuously.  This also causes my fans to run all the time.

**To Reproduce**
1. Install Robot Framework Language
2. Restart PyCharm and wait.

**Expected behavior**
No significant change in processor activity should happen when sitting idle.

**Screenshots**
![image](https://user-images.githubusercontent.com/84199068/118306983-51cf2480-b4a7-11eb-8a3f-48b5828e82af.png)

**Versions:**
 - OS: Windows 10
 - Robot Framework Language Server Version 0.16.0
 - PyCharm 2021.1.1

**Comment by fabioz** [comment]
Can you expand to show the contents of the process below the CPU? 

-- I'm curious to know which process is taking up the CPU usage in your use-case.

Something as:

![image](https://user-images.githubusercontent.com/117621/118309821-2eff3900-b4c4-11eb-986c-4ae5381bf351.png)

**Comment by cookindutch** [comment]
![image](https://user-images.githubusercontent.com/84199068/118314471-6b756980-b4b1-11eb-8990-c2672ee9ddcf.png)

**Comment by cookindutch** [comment]
Sorry. I copied the wrong screen.  
![image](https://user-images.githubusercontent.com/84199068/118314552-8811a180-b4b1-11eb-8c8b-3642c98725a2.png)

**Comment by cookindutch** [comment]
![image](https://user-images.githubusercontent.com/84199068/118314708-bbecc700-b4b1-11eb-9301-174111820621.png)

**Comment by fabioz** [comment]
Is it possible for you to attach a profiler and send me the related pstats files from that?

To do that, please do the following:
1. Install PyVmMonitor (download it at: https://www.pyvmmonitor.com/download.html) -- you can use the 15 days trial.
2. Attach it to the process which has the high CPU usage (following the steps from: https://www.pyvmmonitor.com/attach_to.html). Note: you can right-click the tabs in the process explorer and select `PID` so that you know which `PID` should be profiled.
3. Save the pstats to a file and attach them to this issue.
i.e.:
![image](https://user-images.githubusercontent.com/117621/118532209-12aa0900-b71d-11eb-9d83-433085dfc5f5.png)

**Comment by cafe88** [comment]
I hope i've done this right. If not, please let me know ;-)

This is the log from one of the four Python processes which lead to high cpu load

[test.zip](https://github.com/robocorp/robotframework-lsp/files/6507177/test.zip)

**Comment by fabioz** [comment]
Thanks for the logs... apparently the filesystem polling is responsible for that.

I guess the filesystem polling is too tied to work well on my system. Also, apparently there's polling from several processes at once.

I'm working on fixing this (both with a better polling algorithm -- or using native filesystem notifications when possible -- to work better on other machines and to make the polling work on a single process and have other processes talk to it instead of having polling in multiple processes).

**Comment by cafe88** [comment]
Thank you for the quick reply!
Maybe I have another useful information for you:

I've set up a test robot-file with only one Test case with only one Log in it (especially without using additional Libraries) and that does not seem to be a problem, no high CPU load.
If i can help you with any other information, please feel free to tell me what you need.

**Comment by fabioz** [comment]
Yeap, the filesystem polling speed is pretty much related to the number of files you have under the workspace, so, on tiny projects it shouldn't be a problem.

**Comment by fabioz** [comment]
This should be fixed in version `0.17.0` (which I hope to release next week).

**Comment by cafe88** [comment]
Seems to be working fine, thank you very much for your quick reaction!
