### ISSUE TITLE
Issue with plugin "intellibot @seleniumlibrary patched"

### ISSUE THREAD

**Issue by judahshaik** [robocorp/robotframework-lsp#388]
Hi team,
My Pycharm doesn't work this plug (intellibot @seleniumlibrary patched) to work with .robot files. also .robot files are not recognizing, and auto suggestions as well not working.
after installing this plugin it  will prompt to restart IDE and once it is restarted Pycharm throws an error like 
(" Exception in Plugin **intellibot @seleniumlibrary patched**. `Disable plugin`
This plugin is not a production of JetBrains. Please report this ")

I have updated all required files to latest- Selenium, selenium library, Robotframework selenium2library, Robotframework seleniumlibrary, etc.

**Comment by fabioz** [comment]
This plugin isn't the intellibot plugin, it's the `Robot Framework Language Server` (https://plugins.jetbrains.com/plugin/16086-robot-framework-language-server).

If you want to use the `Robot Framework Language Server`, please uninstall other Robot Framework related plugins (such as Intellibot) and install the `Robot Framework Language Server`.

Otherwise, if you want to use Intellibot and have an issue with it, please file an issue to the Intellibot plugin.
