### ISSUE TITLE
Issue with "IntelliBot @SeleniumLibrary Patched" plugin

### ISSUE THREAD

**Issue by judahshaik** [robocorp/robotframework-lsp#389]
Hi team! Greetings!

I am unable to use "**IntelliBot @SeleniumLibrary Patched**" plugin in PyCharm community edition 2021.1.1 and Python 3.9.

Pycharm throwing an error like the below screenshot

![RobotPluginError1](https://user-images.githubusercontent.com/85666435/121577944-bf8b5380-ca47-11eb-95ca-329b351bae6d.JPG)

It seems this plugin is not a production of JetBrains and referred me to report it, however i have downloaded from the official site( [](https://plugins.jetbrains.com/plugin/10700-intellibot-seleniumlibrary-patched) )
https://plugins.jetbrains.com/plugin/10700-intellibot-seleniumlibrary-patched 
Also auto suggestions for .robot files are not showing and it's not working. please lookinto this 
I have already installed all required packages and as below:

py                              1.10.0
requests                        2.25.1
robotframework                  4.0.3
robotframework-jsonlibrary      0.3.1
robotframework-pythonlibcore    2.2.1
robotframework-requests         0.9.1
robotframework-selenium2library 3.0.0
robotframework-seleniumlibrary  3.3.1
selenium                        3.141.0
setuptools                      56.0.0

Thanks in advance

**Comment by fabioz** [comment]
@judahshaik you're reporting at the wrong tracker.

This tracker is for the Robot Framework Language Server (https://plugins.jetbrains.com/plugin/16086-robot-framework-language-server).

If you want to use the Robot Framework Language Server, please uninstall other Robot Framework related plugins (such as Intellibot) and install the Robot Framework Language Server.

Otherwise, if you want to use Intellibot and have an issue with it, please file an issue to the Intellibot plugin tracker.

**Comment by judahshaik** [comment]
Hi thanks, 

but I am getting the same error with the "**Robot Framework Language server - 0.18.0**"  .robot files are recognised with this plugin but no auto-suggestions not recognising keywords.

I have uninstalled all Intellibot related plugins.


![RF Language server](https://user-images.githubusercontent.com/85666435/121643007-f183d080-caae-11eb-9576-f8b4247c0fd4.JPG)
