### ISSUE TITLE
Detecting duplicated variable across project

### ISSUE THREAD

**Issue by fdaguin** [robocorp/robotframework-lsp#405]
**Is your feature request related to a problem? Please describe.**

See robotframework/robotframework#2970.

**Describe the solution you'd like**

I want the LS to detect if any variables share the same name across all the resource files of a project. The variables to be *audited* will be the ones either defined:

- through variable files
- inline, under a `*** Variables ***` section

**Describe alternatives you've considered**

Requesting this feature in [robotframework-robocop](https://github.com/MarketSquare/robotframework-robocop) through MarketSquare/robotframework-robocop#399, but it will not be implemented.

**Comment by fabioz** [comment]
I believe there are 2 approaches to this.

Right now the simpler one would be that when doing code-analysis for a given file and going through the imports, it could check for dependencies if some duplicate happens and if it does signal the conflict (on the currently open file which imported the conflicting variables).

A second approach would be having a global variables index (which isn't currently available) and then on code-analysis verify that the keywords from a given resource don't match any on that global variables index on the actual global variable declaration.

I believe the first approach would be reasonable for this and should be straightforward to implement in code (whereas the 2nd is much harder due to that index creation -- keeping things up-to-date isn't straightforward... and not having the index, where it'd need to traverse all the files at each code-analysis request is prohibitive due to its costs).

I don't know when I'll be able to tackle this though, so, I'll add some comments here if someone is interested in tackling it and providing a pull request:

The steps here would go something as creating a collector for the variables and when a variable with the same name is collected the 2nd time, it'd create an error message (for simplicity it could be initially reported at the first line of the document).

The code analysis entry point is: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/src/robotframework_ls/impl/code_analysis.py, so, the implementation should create a new variables collector and then use the `collect_variables` at https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/src/robotframework_ls/impl/variable_completions.py#L381 to analyze all the variables reached.

**Comment by fabioz** [comment]
Note: this would also require tests.

Code-analysis tests are done in: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/tests/robotframework_ls_tests/test_code_analysis.py (it should be pretty straightforward to create a new one based on the existing tests there).
