### ISSUE TITLE
RF Lang. Server plugin for Pycharm not detecting keywords in custom library file.

### ISSUE THREAD

**Issue by medic8601** [robocorp/robotframework-lsp#424]
**Describe the bug**
We have a custom library file written in python CustomLibrary.py (original I know =D ).
Library is imported using the standard "Library" import call for Robot Framework.

![Screen Shot 2021-08-20 at 4 02 17 PM](https://user-images.githubusercontent.com/45071762/130287616-bd59a519-ba8f-4dda-a027-ef0393a33f72.png)

The attempted keyword calls are prefixed with the filename (ex.- CustomLibrary.My Keyword) and they are not receiving any code syntax highlighting, auto-completion, and they are underlined with the red squiggly line indicating an error of "Undefined Keyword".

![Screen Shot 2021-08-20 at 2 41 43 PM](https://user-images.githubusercontent.com/45071762/130287523-49018cb5-359f-46ee-b168-a1eb095633c9.png)

![Screen Shot 2021-08-20 at 4 04 06 PM](https://user-images.githubusercontent.com/45071762/130287773-38640bc8-462e-4e86-b0c3-4afa5477268d.png)

The Robot Framework dry runs and full test runs work as expected. Just the plugin that is not working as expected.

**To Reproduce**

1. Create a custom robot framework library package and save in local repo.
2. Add folder containing custom package to PYTHONPATH in the Language server settings ( )
3. Create Robot Framework suite file that uses keywords in custom library.

**Expected behavior**
All Robot Framework Language Server features should work the same as it does for Library packages that reside in the python site-packages folder. These include:

1. Navigate to file
2. Navigate to keyword
3. Library import syntax highlighting
4. Keyword syntax highlighting
5. Keyword auto-completion

**Versions:**
 - OS: Windows 10
 - Robot Framework Version 4.0.3
 - Robot Framework Language Server Version 0.21.0
 - Client Version PyCharm Professional Edition 2021.2 Build PY-212.4746.96

**Comment by fabioz** [comment]
@medic8601 thank you for the report... 

The most common culprit here is that there's some issue when generating the libdoc for your custom library. 

Please see: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-proceed-if-keywords-from-a-library-are-not-being-resolved for how to proceed in this case.

Please reopen the issue if you're still unable to make it work with those instructions (please include the related logging in that case -- see: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/reporting_issues.md for details).

**Comment by Massukio** [comment]
@fabioz I know this was closed. I am just curios to ask if user can disable code analysis like this by configure any file?
I read a lot documents and non of them mention that I can disable robotframework undefined warning.

**Comment by fabioz** [comment]
@Massukio That's not really related to `.robocop` (this check is done by the language server itself) and unfortunately there's currently no way to disable that check (as that'd also mean that things such as code-completion wouldn't really work for such keywords, so, I'm not sure disabling is ideal).

If you have some particular case where you can't get it to create the `.libspec` after following the steps provided in https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-proceed-if-keywords-from-a-library-are-not-being-resolved, please create a separate issue outlining the problems you have.

**Comment by Massukio** [comment]
@fabioz Thank you for the information.
I had modified my library content and now it's loadable. The undefined keyword warning is gone.

However, I has an issue at **Go To Definition** ..
This is my special case, but I want to ask if **Go To Definition** works with decorators?

I had modified robotkeyword for my own purpose
```
def keyword(name=None, tags=(), types=()):

    def _method_wrapper(func):

        def _passargs(self, *args, **kwargs):
            .. some codes ..
            return func(self, *args, **kwargs)

        _passargs.robot_name = name
        _passargs.robot_tags = tags
        _passargs.robot_types = types

        return pass_argument

    return _method_wrapper
```

With this change, the **Go To Definition** always go to the `def _passargs .. line instead of real function location.
Is there any chance I can have **Go To Definition** works fine with this decorators?

**Comment by fabioz** [comment]
Well, the language server is mostly a consumer of the `.libspec` which is generated by `robot.libdoc` from `Robot Framework` itself. The `.libspec` contains the filename/line for each definition, so, the fix here so that the correct filename/line is collected is something that needs to be done in `Robot Framework` itself.

As such, I suggest you report this to https://github.com/robotframework/robotframework/issues -- when you report it there, please mention this issue so that I can follow it too.

**Comment by Massukio** [comment]
@fabioz The issue is actually occurred due to my modification.
I re-write the decorator to preserve the attributes in nested decorator, including functions' soure filename and source line. And the `.libspec` now generates correct info of keyword func successfully.

Thank you for helping me to resolve this issue :)
