### ISSUE TITLE
option to restart the language server

### ISSUE THREAD

**Issue by DetachHead** [robocorp/robotframework-lsp#476]
**Is your feature request related to a problem? Please describe.**
often the lsp will start reporting false positives which are often fixed by reloading vscode. it would be nice if i could just restart the LSP instead though, like you can with python and other plugins that use language servers
![image](https://user-images.githubusercontent.com/57028336/138002625-9c583abb-2f6f-4db3-b80a-b9faf32ead8e.png)

**Describe the solution you'd like**
an option in the F1 menu to restart the lsp

**Comment by ashwinmenkudle** [comment]
Many language servers provide a restart option so that we could get out of the unthinkable problems.
It acts as a workaround till the problem is fixed.

Here is the following case where restart would be useful.

Use custom keywords from the python file.
Library           ../lib/Xyz.py
Rename the python file and class
Now the cache cause problems.
Problems are reported for ambiguity keyword calls.

**Comment by fabioz** [comment]
This was done in: `0.34.0 (2021-12-16)` (https://github.com/robocorp/robotframework-lsp/commit/a330bfa9fac94f01a27449141a325a7eaff9823a)

![image](https://user-images.githubusercontent.com/117621/151583084-961476b6-ef58-415d-9969-a4fb51839508.png)
