### ISSUE TITLE
Add Keyword parsing (completion and goto) for Keywords in Settings

### ISSUE THREAD

**Issue by Snooz82** [robocorp/robotframework-lsp#49]
Hi Fabio,

Currently no Keyword completion and no Go To Definition is possible for Keywords in settings.
Behind `Suite Setup` or `Template` in settings Section and also behind `[Setup]` etc in test cases and keywords

```
*** Settings ***
Suite Setup    Log    This is SuiteSetup
Test Setup    Set Log Level    Trace
Test Template    This is the Test
Test Teardown    Log    now its over
Suite Teardown    Log To Console    This is the End

*** Test Cases ***
Test1    Hello
Test2    World
Test
    [Template]    None
    [Setup]    Log    this is different
    Log To Console    different test
    [Teardown]    Log    different End

*** Keywords ***
This is the Test
    [Arguments]    ${arg}
    Log To Console    ${arg}
    [Teardown]    Log    Not completed
```

**Comment by fabioz** [comment]
@pekkaklarck, can you confirm that the tokens where keywords appear in the ast are in `KeywordCall.keyword` statements and in `Fixture.name`? Is there some other place I'd be missing?

Also, as a note, I'm starting to rely more on the structure of `robot.parsing.model.statement` (so, even small changes could break the language server there -- as was the case for the recent change for `SectionHeader.value` to `SectionHeader.name`, so, it'd be nice if you can give me a heads up when you change things in the parsing -- I'm testing against the `master` to catch those, but clients may be slower to update -- I guess that if you envision more changes like that happening, I should probably prioritize vendoring `robotframework` so that clients aren't broken due to that).

**Comment by pekkaklarck** [comment]
Keywords could also be in Template. I'm on mobile and cannot easily check which node type or attribute name it is.

**Comment by pekkaklarck** [comment]
Sorry for the API change. It didn't occur to me _that_ attribute was already used externally. I learned my lesson and was already earlier planning to avoid API changes after RF 3.2 final.
