### ISSUE TITLE
pycharm plugin not recognising selenium library keywords

### ISSUE THREAD

**Issue by jacosmuts** [robocorp/robotframework-lsp#504]
Good day

I am revisiting robotframework after some years and would really like to use pycharm (since I use it for python work) but using the robocorp plugin does not recognise selemium keywords.

![image](https://user-images.githubusercontent.com/5435503/141186167-c65baf62-6350-490f-b6d6-0a7979225d5f.png)

I'm not sure if I missed a step on installation.

My environment:
Windows 10 64bit
PyCharm 2021.2.3 (Professional Edition)
Python 3.10
robotframework 4.1.2
robotframework-seleniumlibrary 5.1.3
robotframework-lsp 0.28.0

Any advice would be greatly appreciated.

Thank you
Jaco

**Comment by KotlinIsland** [comment]
Use playwright, it's way better.

**Comment by jacosmuts** [comment]
That is interesting (not the response I expected on this forum) :)

Any other thoughts on playwright, or my original question?

**Comment by KotlinIsland** [comment]
https://github.com/MarketSquare/robotframework-browser

There's this support for playwright in robot.

**Comment by KotlinIsland** [comment]
https://plugins.jetbrains.com/plugin/17424-intellibot-patched

There's this alternative plugin if the lsp isn't working properly.

**Comment by jacosmuts** [comment]
Thank you KotlinIsland

I am browsing playwright now, it does look interesting. 

I have installed intellibot-patched in the meantime and it is working fine. But you have now sent me down another rabbit-hole.

Tempted to keep this thread open for questions, but I guess I should close it, since this discussion is going in a different dirrection now.

Thank you

**Comment by KotlinIsland** [comment]
the robot plugin nightmare in PyCharm is an endless rabbithole :)

Don't close it.

**Comment by fabioz** [comment]
@jacosmuts it is a bit weird that it didn't work out of the box with the `Robot Framework Language Server` plugin for PyCharm (both libraries should work with it).

The usual culprit here in PyCharm is that you're not using the same Python where you have the plugin installed (otherwise it'd mean that there was some problem generating the libspec for that library).

If that's actually your case, you need to specify the proper Python in `File > Settings > Languages & Frameworks > Robot Framework` (`Global` if you want to save the settings in your user configuration or `Project` if you want to save it in your project). Then, you can change `Language Server Python` to point to the `python` executable that has the library installed.

p.s.: this is already reported in: https://github.com/robocorp/robotframework-lsp/issues/370

If this isn't your case, it'd be nice to have the logs when this happens (i.e.: if this isn't working out of the box, this would be a bug).

As a note, if you do decide to use the `Robot Framework Language Server`, please make sure you uninstall `intellibot-patched` as conflicts are bound to happen if both are installed...

**Comment by jacosmuts** [comment]
Thank you @fabioz 

I will have a look this evening and report back.

**Comment by mdks2010** [comment]
![image](https://user-images.githubusercontent.com/53963129/141313655-14eff039-6113-4dd5-8b29-1a1016bbaa9a.png)

**Comment by fabioz** [comment]
Closing as no additional feedback was given.
