### ISSUE TITLE
Request: Always display the library name when suggesting a keyword

### ISSUE THREAD

**Issue by janipalsamaki** [robocorp/robotframework-lsp#507]
The code auto-completion sometimes lists the library that provides the given keyword:

```
Open Available Browser (RPA.Browser.Selenium)
```

I find that additional information very valuable, being able to see the providing library.

Some auto-complete suggestions do not show the providing library, so there is probably some logic behind that.

Would it be a good idea to _always_ show the library name, too? At least I find it super useful.

**Comment by fabioz** [comment]
I think that's interesting.

As a note, I think it'll show that info only if the library will be imported automatically as a part of applying the completion (otherwise, as it's already imported, that info is not shown) -- it's a bit tricky in that if it's always shown, it may be hard to know what would add a new import and what is already imported, but I guess this could be shown in a different way too...
