### ISSUE TITLE
Not detecting keywords from user library

### ISSUE THREAD

**Issue by sivaram-vu** [robocorp/robotframework-lsp#514]
Keywords are not detected from user resource file

**To Reproduce**
1. Create a library file in python_library/test.py
2. create a robot keyword and import the library in settings section(Library    python_library/test.py)
3. observe that function in test.py library is not suggested as keyword

**Expected behavior**
Should suggest the functions from imported library as keywords.

**Versions:**
 - OS: RHEL8
 - Robot Framework Version: 4.1.2
 - Robot Framework Language Server Version: 0.27.0
 - Client Version: intellij 2021.2.3

**Comment by fabioz** [comment]
This does work for me. 

Please check: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-proceed-if-keywords-from-a-library-are-not-being-resolved to see if it can help you there.

If you still can't figure it out, please provide the logs so that it's possible to check what's happening in your case (see: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/reporting_issues.md).

**Comment by fabioz** [comment]
Closing since no additional feedback was given.

Please reopen when you're able to provide the logging if this is still an issue for you.
