### ISSUE TITLE
Argument names not showing in auto complete, only default values.

### ISSUE THREAD

**Issue by JoneSabino** [robocorp/robotframework-lsp#53]
Argument names are not showing in auto-complete, only default values. 

Actually, it is ignoring ${} and everything that is inside it.  made a test with `'${foo}'=bar` and got `''=bar` using auto-complete.

See the example below:
![image](https://user-images.githubusercontent.com/21135355/80290694-79791080-871d-11ea-8239-939d2e594eb1.png)
![image](https://user-images.githubusercontent.com/21135355/80290710-9c0b2980-871d-11ea-9571-0b7aff040dcc.png)

**Comment by Snooz82** [comment]
@JoneSabino Just as a remark: it is very helpful if you exactly write and analyze how this is reproducible and may how it does not appear.

@fabioz this happens only on user keywords and scalar arguments. Python Library keywords are not affected. Agruments like `@{args}` and `&{kwargs}` are created like they are written. Which is also not like they should.

I would assume, that in the parsing of the arguments names there is a bug because when i change the names of the arguments to just names without the ${syntax} it works. But this is no valid robot code.

![DAED9B9A-CC28-4A83-A91C-F248F261D635](https://user-images.githubusercontent.com/41592183/80293264-515dd180-875e-11ea-89ce-6ac41866a9f5.png)

By the way. I would assume, that @{args} (*args in python) and @{kwargs} (**kwargs in python) should be also interpreted and completed without the ${syntax}

@pekkaklarck do you agree with me that these variable arguments should be completed like they are in the LibSpec at the moment?
(Maybe better `@args`, but for now the libspec has the star as syntax)
@{args} -> *args
&{kwargs} -> **kwargs
