### ISSUE TITLE
remove the `Run | Debug` buttons

### ISSUE THREAD

**Issue by DetachHead** [robocorp/robotframework-lsp#539]
now that there are run buttons on the gutter, the old ones are redundant

![image](https://user-images.githubusercontent.com/57028336/150079089-059de6e7-fd1c-4cb3-abbf-e772cbadd5b4.png)

**Comment by emilszymecki** [comment]
I have additional problems with this button

When i run task ctrl+shift+p -> Run Robot
${OUTPUT_DIR} = ${CURDIR}${/}output
When i click this button
${OUTPUT_DIR} = ${CURDIR}

**Comment by fabioz** [comment]
@emilszymecki the issue here is that when you launch a robot you're effectively running the command line defined in your `robot.yaml`, whereas when you click a run/debug button (or the green arrow in the gutter) you're doing a "bare" run without such customized arguments -- it's still possible to customize that run though by following the instructions at:

https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-configure-the-launch-from-a-code-lensshortcut

With those instructions it should be possible to add `"args": ["--outputdir", "output"]` when those shortcuts are activated.

**Comment by fabioz** [comment]
As a note, this is now available in a pre-release (0.42.2).

See: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/changelog.md for all that's changed in the pre-release.
