### ISSUE TITLE
Unresolved Libraries - Special Case ( DataDriver )

### ISSUE THREAD

**Issue by pedrolcd** [robocorp/robotframework-lsp#559]
**Describe the bug**

Hello,

After installing DataDriver, which is a special library according to docs / developed by @Snooz82 , I am getting a problem 
with the following output: `Unresolved library: DataDriverrobotframework`

The  language server is correctly installed and my tests are running accordingly.

Many of my test cases will require the usage of DataDriver, and I want to avoid a _bloodbath_ in **VSCode** file directory.
Any suggestion in order to ignore this type error?

Thanks in advance. Cheers 

**Screenshots**
![Screenshot 2022-01-28 at 14 17 22](https://user-images.githubusercontent.com/36089983/151564109-ee2f2e71-84c5-46c8-a342-7adbf13aead6.png)

**Comment by fabioz** [comment]
I just investigated. 

The issue is that the language server is considering the library invalid because it has no keywords exported (which is definitely the wrong thing to do as the library is valid, it just doesn't have any keywords in this case -- specifically: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/src/robotframework_ls/impl/libspec_manager.py#L748).

I'll try to fix this for the next release.
