### ISSUE TITLE
Investigate case where completions stop appearing in the interactive console

### ISSUE THREAD

**Issue by fabioz** [robocorp/robotframework-lsp#570]
https://forum.robocorp.com/t/auto-complete-stop-working-in-interactive-console-in-vscode/1411

**Comment by kleemc** [comment]
[log.zip](https://github.com/robocorp/robotframework-lsp/files/8057719/log.zip)

Log attached.

I did some very basic steps in the interactive window.   open available browser,  go to google,  and then the auto completion window stop appearing.   This issue is very repeatable but not always after the same command.   Usually it'll appear after about 5 to 6 commands.

**Comment by fabioz** [comment]
The issue isn't really that something became broken, rather, when the line was entered the editor was in `snippet` mode (so, pressing `esc` once would make things work again and a `Ctrl+Space` would still re-request completions).

I've just fixed it so that the editor leaves snippet mode when a line is evaluated.
