### ISSUE TITLE
Leaf file doesn't autocomplete from trunk, but test case that imports trunk allows leaf file to use trunk keywords

### ISSUE THREAD

**Issue by testventure** [robocorp/robotframework-lsp#587]
**Describe the bug**
I have a resource file (suite-resource.robot) that has keywords that are for a specific test-suite (test2.robot).  I import that file into a general resource file which has its own keywords (main-resource.robot).  In VSCode, the LSP plugin says that there is no definition for Keywords that are declared inside main-resource.robot.  The curious part to me is that if I run test2.robot while there are calls for keywords in suite-resource.robot that are from main-resource.robot, it works.  So there seems to be something different between the LSP context and the running test-case's context with regards to what keywords suite-resource.robot has access to.

**To Reproduce**
I have provided a zip file of a mockup of my files.  
I suppose just run test2.robot.  It runs without any keyword errors even though suite-resource.robot calls keywords from the trunk.

**Expected behavior**
Looking at it I'm not sure what I expect.  Perhaps the way I have things organized is silly.  I guess, since it runs successfully I expect that suite-resource.robot calling a keyword from the trunk means it should be able to "go to definition" or auto complete.

**Versions:**
 - OS: Windows 10
 - Robot Framework Version: 4.1.3
 - Robot Framework Language Server Version: 0.41.0
 - Client Version: 1.64.2

[lsp-test.zip](https://github.com/robocorp/robotframework-lsp/files/8142931/lsp-test.zip)

**Comment by fabioz** [comment]
Yes, the structure is indeed strange... think of the following: if you executed the keywords from `suite-resource.robot` directly, those keywords would fail.

In general, the language server needs to analyze the structure statically, so, it's not possible for it to detect that the `suite-resource.robot` is always only importable through a path which would have imported the `main-resource.robot` before.

Think of it as the following: if you opened just that file without knowledge of the remainder of the structure, would you expect an error or not? -- this is the situation of the language server when you open it -- it has no way of the runtime constraints to have something defined.

My suggestion would be to change your structure so that dependencies are explicit.

In this particular case the `test2.robot` would import the `suite-resource.robot` directly and the `suite-resource.robot` would import the `main-resource.robot`...

**Comment by testventure** [comment]
So, here's the thing.  These suite-resources are sometimes used in other suites.  For example, login tests have their own resources.  However, many tests use the resources for login to perform actions after login.  The way I have it, I have access to all the resources from within the test suites without one monster resource file.  If I did it the other way around, I would need to import every resource file individually or move every KW that is used in more than one file into the main file again making for a very large file.

I recognize my setup is weird.  It was just the best way I could think of to organize things a bit.  Perhaps I just need to import each file individually every time as necessary.

**Comment by fabioz** [comment]
> I recognize my setup is weird. It was just the best way I could think of to organize things a bit. Perhaps I just need to import each file individually every time as necessary.

I think that'd be better...

As a note, I'm closing this issue -- it'd be a herculean effort to support that use case properly (because the extension would need to start seeing the dependencies backwards and keeping that in sync seeing the codebase as a whole and not having to just look at the current file for dependencies).
