### ISSUE TITLE
Resource imports with Builtin Operating System variables are marked as errors

### ISSUE THREAD

**Issue by weltings** [robocorp/robotframework-lsp#599]
**Describe the bug**
Resources with built-in path variables do tnot get resolved

**To Reproduce**
Create the following files:
C:\Temp\example\foobar.robot
C:\Temp\example\foobar.resource
C:\Temp\example\foobar.py

The contents of foobar.robot should be:
*** Settings ***
Resource    ${EXECDIR}\foobar.resource
Resource    ${CURDIR}\foobar.resource
Resource    C:\Temp\example\foobar.resource
Library        ${EXECDIR}\foobar.py
Library        ${CURDIR}\foobar.py
Library        C:\Temp\example\foobar.py

**Expected behavior**
Note that all 3 Library references get resolved correctly. 
However the Resources with ${EXECDIR} and ${CURDIR} do not get resolved and are marked as error with red underline.
I would expect all resources to be resolved correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/33200263/157973447-fc4d0f39-44d4-4e18-ab4e-7d97e0fc6bb4.png)

**Versions:**
 - OS: Windows 10
 - Robot Framework Version: 4.0
 - Robot Framework Language Server Version: PreRelease
 - Client Version: VSCode 1.65.1

**Comment by weltings** [comment]
Maybe I can look into this. If you can show me the code parts that need to be changed. It seems to work for Library imports but not Resource imports. Can you point out the code for each one?

**Comment by fabioz** [comment]
Well, ${EXECDIR} is really expected not to be defined because it depends on your current working directory when you execute (which can't be known prior to execution).

See: https://github.com/robocorp/robotframework-lsp/issues/263#issuecomment-941276231

${CURDIR} should work though (as it resolves to the directory where the robot file is defined and is supported).

Please reopen if you're able to have a working example where ${CURDIR} doesn't work.
