### ISSUE TITLE
robotframework-intellij: vulnerability CVE-2020-8908

### ISSUE THREAD

**Issue by jokinr** [robocorp/robotframework-lsp#645]
**Is your feature request related to a problem? Please describe.**
PyCharm plugin robotframework-intellij uses old version of com.google.guava:guava which contains vulnerability CVE-2020-8908

**Describe the solution you'd like**
Version upgrade

![image](https://user-images.githubusercontent.com/46047015/162419588-4e47b582-b7dc-4616-81bd-6f7557d87ab1.png)

**Comment by fabioz** [comment]
This dep actually comes from `org.eclipse.lsp4j` (so, `org.eclipse.lsp4j` itself needs to be updated).

Still, that vulnerability doesn't seem to be applicable since `createTempDir()` isn't used in the language server nor in `lsp4j`, so it's pretty much a non-issue.

Given that, I'm closing this issue (there aren't plans to change/update `lsp4j` in the short-mid term unless there's really a critical issue or someone volunteers to do the update and test it accordingly -- if you're interested in doing it, please let me know and I'll reopen it).
