### ISSUE TITLE
question

### ISSUE THREAD

**Issue by otemek** [robocorp/robotframework-lsp#651]
Hi
I don't wanna be rude but isn't it that below methods:
robocorp-code\codegen\convert.py::convert_case_to_camel()
robotframework-ls\codegen\convert.py::convert_case_to_camel()
are duplicating each other and what's more important are not used anywhere on robotframework-lsp project?

Maybe it's intentional, e.g. it's used somewhere and I couldn't catch that, or is it for future purpose :)

**Comment by fabioz** [comment]
Well, that could be useful in the future if we want to generate javascript code for something (I'm not sure if it was used or if it was added as is directly because I copied from another module I had around -- the 2nd option is probably more likely).

Note that while that code could be moved to a common base (in this case the common code would need to be moved to `robocorp-python-ls-core`), I'm not sure it's worth it -- it could just be deleted, but it has potential to be used in the future, so, I'd rather just leave that dead code there...

Note that any code in `codegen` is only run during development and doesn't need tests and in general can afford to be a bit less strict than code which is actually run when the user is running the language server...
