### ISSUE TITLE
[Feature Request]Enable Intellisence for Multiline Composite Command

### ISSUE THREAD

**Issue by Deep-Adhikary** [robocorp/robotframework-lsp#68]
![image](https://user-images.githubusercontent.com/13049680/81897708-d3f6e580-95d4-11ea-88c9-2c8f94d16747.png)
![image](https://user-images.githubusercontent.com/13049680/81897767-e709b580-95d4-11ea-86d7-ed85cf9149af.png)

**Comment by Snooz82** [comment]
@Deep-Adhikary 
The issue here is not the multi line, but that the keyword `Run Keyword and Return Status` has a String as first argument. Internally it calls that keyword, but this is not a keyword by language.

Imho it would be nice if we would have a special handling of these BuiltIn Keywords, but i think at the moment this should be low priority because it is not real part of the language.

**Comment by fabioz** [comment]
I'm closing this issue for now to shorten the the backlog.

Note: I'm marking things that may be done later with the `maybe later` tag so that it's searchable in the future (so, this is closed as there are no plans to tackle it in the short/mid term -- it can be reopened if someone provides a pull request or if higher priority items are no longer available).
