### ISSUE TITLE
Sometimes the plugin is unable to link to py files

### ISSUE THREAD

**Issue by lynhbn** [robocorp/robotframework-lsp#680]
**Describe the bug**
Sometimes the plugin is unable to link to py files

**To Reproduce**
1. Install the plugin
2. Invalidate caches - Restart the IntelliJ IDE
3. See that there's some errors importing py files. Some can still be importing fine. Does not happen with other plugins (IntelliBot)

**Expected behavior**
3. Should import correctly and can navigate to each keywords, variables in that py file

**Screenshots**
<img width="272" alt="image" src="https://user-images.githubusercontent.com/52777697/168566512-4ef48cbd-35f1-4178-bfb9-bd61f325ffda.png">

**Versions:**
 - OS: Windows 11
 - Robot Framework Version: 5.0.1
 - Robot Framework Language Server Version: 0.47.2
 - Client Version: IntelliJ 2021.2.4

**Comment by fabioz** [comment]
What's the actual error message you have at that location? -- you can see that at the `Problems` tab in Intellij.

**Comment by lynhbn** [comment]
```Unresolved library: ./custom_locator.py.
Error generating libspec:
Importing library 'custom_locator' failed: RobotNotRunningError: Cannot access execution context
Consider adding the needed paths to the "robot.pythonpath" setting
and calling the "Robot Framework: Clear caches and restart" action.```

intelliBot still navigating fine with this one.
I have tried invalidate caches and restart, but still persists

**Comment by fabioz** [comment]
The issue here is that the `.libspec` could not be generated properly for the library (so, its keywords won't be recognized). You need to change the library so that it can be imported/instanced without requiring runtime information from robot framework.

See: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-proceed-if-keywords-from-a-library-are-not-being-resolved (`3. The library requires runtime information to be imported.`) for more details.
