### ISSUE TITLE
File system notifications not handling `.yaml` (variable) files

### ISSUE THREAD

**Issue by rarajabs** [robocorp/robotframework-lsp#710]
**Describe the bug**
RF Language Server in VS Code is not able to recognise/ interpret built in variables for directories

**To Reproduce**
Import  resources/ variables in settings section on robot file.
```
Variables           ${CURDIR}${/}variables${/}common variables.yaml
```

**Expected behavior**
VS Code will not show any error and interpret those built in variable to correct values

**Screenshots**
![image](https://user-images.githubusercontent.com/1460421/180404630-993e797f-c315-40db-b7cc-712b216420a2.png)

![image](https://user-images.githubusercontent.com/1460421/180405082-41a0023e-ea35-4d40-8635-64f92721b01c.png)

**Versions:**
 - OS: Win 10
 - Robot Framework Version: 5.0.1
 - Robot Framework Language Server Version: 0.49.0
 - Client Version: VSCode 1.69.2

**Logs**
None

**Comment by fabioz** [comment]
Buitin variables are resolved (the only builtin variable not resolved is `EXECDIR` because it's not stable as it relies on runtime information, so, you need to define it yourself using `robot.variables` -- see: https://github.com/robocorp/robotframework-lsp/issues/263#issuecomment-941276231 to point to the place you want it resolved).

As for `CURDIR`, it does resolve to the directory containing the current `.robot` file and it works for me in the example I have here... if you still can't get `CURDIR` to resolve, please provide a sample project where that happens to make sure we're looking at the same thing.

**Comment by fabioz** [comment]
Actually, I was able to reproduce it with `Variables           ${CURDIR}${/}variables${/}common variables.yaml` (so, it's not directly related to `${CURDIR}`, but that particular usage... I'll investigate to know what's causing it).

**Comment by fabioz** [comment]
Humm, I found a caching issue here (so, it's not related to variable resolution) -- clearing the caches using the command: `Robot Framework: Clear Caches and restart Robot Framework Language Server` makes the issue go away (I'll take a look at fixing the underlying issue).

I can reproduce it by first creating a file with:

```
*** Settings ***
Variables           ${CURDIR}${/}variables${/}common variables.yaml
```

and only creating the `common variables.yaml` file afterwards.
