### ISSUE TITLE
VSCode extension does not work properly when installed on a Hyper-V VM through VS-Code Remote-SSH

### ISSUE THREAD

**Issue by wlad** [robocorp/robotframework-lsp#72]
Detailed description of the bug or suggestion
----------------------------------------------
I'm using VSCode as remote IDE on a Hyper-V VM (Guest OS == Ubuntu 19.10). Installing the extension on remote host results in below error

![image](https://user-images.githubusercontent.com/64201310/82358605-08203b00-9a07-11ea-89e3-6f5a1d959bf9.png)

```
[Error - 7:17:35 PM] Starting client failed
Launching server using command
/home/wlad/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/bin failed.
```

Extension logs (attach as a file)
----------------------------------------------

not available

Additional Information
----------------------------------------------
1) The extension works as expected when install locally (on Windows host)
2) The extension "Robot Framework Intellisense" works properly on the same remote host, so maybe a good starting point to see how to make robotframeowrk-lsp exentension also work on remote host
![image](https://user-images.githubusercontent.com/64201310/82359487-3b16fe80-9a08-11ea-9ac2-303af946d3e7.png)

**Comment by fabioz** [comment]
I'm closing this issue for now to shorten the the backlog.

Note: I'm marking things that may be done later with the `maybe later` tag so that it's searchable in the future (so, this is closed as there are no plans to tackle it in the short/mid term -- it can be reopened if someone provides a pull request or by me if higher priority items are no longer available).
