### ISSUE TITLE
Unresolved libraries error with .py extension

### ISSUE THREAD

**Issue by adamweld** [robocorp/robotframework-lsp#779]
**Describe the bug**
Language server is failing to resolve some custom libraries when the .py extension is included in the settings Library line.

Error seen here:
![image](https://user-images.githubusercontent.com/525911/195416531-55dcb9eb-92fd-4221-bb29-b40c082a4680.png)

Dropping the .py in this case causes it to import fine:
![image](https://user-images.githubusercontent.com/525911/195416779-831dfb86-da5e-4e70-80d0-b52ce7a294bc.png)

Error text:
```
Unresolved library: DeckLibrary.py.
Error generating libspec:
Initializing library 'DeckLibrary' with no arguments failed: RobotNotRunningError: Cannot access execution context robotframework
```

Notably, executing robot cli on both syntaxes works just fine, as far as I can tell this is limited to the language server.

**To Reproduce**
I'm having trouble reproducing, this just started happening with this specific custom library.

All of my custom libraries are in the same folder, in pythonpath, and have class names that match the module name.

**Comment by fabioz** [comment]
The error:

`Initializing library 'DeckLibrary' with no arguments failed: RobotNotRunningError: Cannot access execution context robotframework`

says that it was not possible to load the documentation for that library (because its constructor needs robot framework running but when just collecting library information robot framework is not running).

Please see the following FAQ and let me know if it has enough information for you to fix the issue: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-proceed-if-keywords-from-a-library-are-not-being-resolved

**Comment by fabioz** [comment]
Closing as no further info was given -- hopefully the FAQ was enough to resolve the problem ;)
