### ISSUE TITLE
Importing library failed: ImportError (Error generating libspec)

### ISSUE THREAD

**Issue by jura84** [robocorp/robotframework-lsp#800]
**Describe the bug**
**A clear and concise description of what the bug is:**

We would like to take your Robot Framework plugin into use but not been successfully yet..
We're using VS Code and also importing custom python libraries.
However, at least one library raises and exception in editor, seems that from LibDoc your plugin is using?

I added few examples below how's the files are constructed.

Python library imports following PIP libraries and also implements a class.
Imports done in the beginning of file before class implementation.

**Python library example:**
import nidaqmx
from nidaqmx.stream_readers import DigitalMultiChannelReader, AnalogMultiChannelReader
from nidaqmx.stream_readers import CounterReader
from nidaqmx.stream_writers import DigitalMultiChannelWriter, AnalogMultiChannelWriter
from nidaqmx.system._collections.physical_channel_collection import PhysicalChannelCollection
from nidaqmx.system import PhysicalChannel, System, Device
from nidaqmx.system.storage import PersistedScale
from nidaqmx import constants
from nidaqmx.task import InStream
import numpy as np
import pandas as pd

class dummy-example:
def __init__(self):
pass

def yada-yada(self):
pass
...

**settings.json example:**

{
    "python.defaultInterpreterPath":"C:/Program Files/Python38/python.exe",
    "robot.completions.keywords.format": "Title Case",
    "robot.pythonpath": [
        "${workspaceFolder}/libs/python",
        "c:/users/joe-doe/appdata/roaming/python/python38/site-packages"
    ],
    "robot.variables": {
        "EXECDIR": "C:/code/"
    }
}

**Error from VS Code plugin:**

Unresolved library: dummy-example.
Error generating libspec:
Importing library 'dummy-example' failed: ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using c:\ProgramData\robocorp\ht\19eac23_b1f3c24_ed8324b2\python.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'
Consider adding the needed paths to the "robot.pythonpath" setting
and calling the "Robot Framework: Clear caches and restart" action.robotframework

**To Reproduce**
**Steps to reproduce the behavior: **
I would assume if people using nidaqmx, numpy and pandas most probably seen this issue

1. Install pip package nidaqmx==0.5.7
2. Install pip package numpy==1.16.1
3. Install pip package pandas==1.0.5
4. Create custom library which imports these (see imports above)
5. Create subfolder in your workspace which contains custom python library
6. Add subfolder to custom python libraries folder into settings.json to configure pythonpath
7. VS Code indicates and error in editor that import failed

**Expected behavior**
API documentation generation and imports work.

Or at least have a possibility to configure from VS Code how deep the LibDoc analyses libraries.
I assume it just tries to import this custom library and after that tries to show API doc.

**Screenshots**
![image](https://user-images.githubusercontent.com/34338587/201326919-47e3c2ee-6622-4234-a118-4655c94e7cb9.png)

**Versions:**
 - OS: Windows 11
 - Python Version (not virtual): 3.8.10
 - Robot Framework Version: 4.1.3
 - Robot Framework Language Server Version: 1.5.0
 - Client Version: VSCode 1.73.1

**Notes**
Please be aware that these versions needs to be used because we use lot of other PIP packages which requires at the moment to have specific Python and Robot versions.

As you see from settings.json. I added site-packages into python path so it can find PIP packages.
Otherwise, plugin will show error that PIP package XYZ not found.

What is curious is that error shows that robocorp plugin is not using my custom Python interepter and it's using something else. Is this, OK?

In config:
"python.defaultInterpreterPath":"C:/Program Files/Python38/python.exe"

In error message:
1. Check that you are using the Python you expect (you're using c:\ProgramData\robocorp\ht\19eac23_b1f3c24_ed8324b2\python.exe),

**Comment by jura84** [comment]
When IT engineer asks a question, problem is solved magically after the question..

The issue was that this needs to be defined.
Is it that your plugin uses different python if not defined in settings.json ?

![image](https://user-images.githubusercontent.com/34338587/201331106-a941142f-f5f1-46b2-b5cd-0a3fb2e5744e.png)

**Comment by fabioz** [comment]
@jura84 the issue here is that if you install `Robocorp Code` as well as `Robot Framework Language Server`, it'll create a separate base environment and it'll use that unless instructed to do so and it'll automatically create separate environments based on your `robot.yaml`/`conda.yaml` and it'll use that for your Robots.

So, you have some choices:
1. Using `Robocorp Code`:

- Actually use `robot.yaml`/`conda.yaml` in your projects using `rcc` (see https://robocorp.com/docs/setup/robot-yaml-format / https://robocorp.com/docs/rcc/overview) in which case the Python environment will be automatically created and managed for you (and external runs would use `rcc` to lauch such Robots).

2. Not using `Robocorp Code`:

- If you don't plan to use Robots, don't use `Robocorp Code` (in which case you can just uninstall it). 
- Set the interpreter you want to use using `Python: Select Interpreter` (from `vscode-python`) and restart VSCode so that the language server starts up with that interpreter.
- Or specify the `robot.language-server.python` to point to the python interpreter you want to use (if you set this, you don't need to set `robot.python.executable` as it'll be the same by default -- you may want to specify `robot.python.executable` if you also need to specify environment variables with `robot.python.env` though, in which case the language server uses one python for running and another for introspecting the environment you want to work with).

**Comment by fabioz** [comment]
p.s.: Closed because it should be fixed through configuring things differently, but feel free to ask more questions.
