### ISSUE TITLE
Error "Multiple values for argument: name" if keyword with argument "name" is used with keywords `Run Keyword *`

### ISSUE THREAD

**Issue by JaPyR** [robocorp/robotframework-lsp#860]
**Describe the bug**
Stumbled across such edge case when named argument from second argument is marked as error when using with keywords `Run Keyword *`.

![image](https://user-images.githubusercontent.com/7773301/212270517-c4d08e8e-3d68-4898-af94-87482f209c61.png)

**Example:**
```robotframework
*** Test Cases ***
DemoCase
    Run Keyword And Continue On Failure    Check Something    name=test
    Run Keyword And Ignore Error    Check Something    name=test
    Run Keyword And Expect Error    *    Check Something    name=test

*** Keywords ***
Check Something
    [Arguments]    ${name}
    Fail    ${name}
```

**Versions:**
 - OS: Windows 11
 - Robot Framework Version: 5.0.1
 - Robot Framework Language Server Version: 1.7.3
 - Client Version: 1.74.2

**Comment by haklir** [comment]
I've been meaning to file this bug at least since October 2022, so apparently sometimes it pays off to procrastinate a little. 😄 👍 In my case I'm calling a keyword written in Python
```
def my_keyword(self, **kwargs):
```
like this
```
    Run Keyword And Expect Error    Error: something meaningful
    ...    My Keyword    name=foo    blah=${EMPTY}    bar=${variable}
```
which triggers the same exact error as in the above screenshot. Should probably also mention that this is totally valid robot code and executes just fine.
