### ISSUE TITLE
How to disable `missing-doc-suite` warning?

### ISSUE THREAD

**Issue by 4nif** [robocorp/robotframework-lsp#861]
Hello

How can we disable warning `missing-doc-suite` warning from the `settings.json`?
I have `.resource` file and contains only `*** Variables ***` 
When I enable robocop lint in `settings.json` VSCode shown warning `missing-doc-sute`

I have try to add `# robocop: disable=missing-doc-suite` after `*** Variables ***` and warning still appear

Is it possible to disable this warning on the specific resource file?

**Comment by fabioz** [comment]
Hello, the language server doesn't really control that, this is controlled by `Robocop`, so, the proper place to ask this is:

https://github.com/MarketSquare/robotframework-robocop/issues

Although you may want to check their docs prior to asking: https://robocop.readthedocs.io/en/stable/

Note: if you install `robotframework-robocop` into your environment it'll use that version, otherwise it'll use a vendored version (the current release is bundled with `robotframework-robocop-2.5.0`).
