### ISSUE TITLE
@CasparQuast there is already a solution: add the proper listeners arguments in the execution.

### ISSUE THREAD

**Issue by CasparQuast** [robocorp/robotframework-lsp#928]
@CasparQuast there is already a solution: add the proper listeners arguments in the execution.

See: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-configure-the-launch-from-a-code-lensshortcut for details on how to do that for shortcuts (such as code lenses, dropdowns or tests).

_Originally posted by @fabioz in https://github.com/robocorp/robotframework-lsp/issues/927#issuecomment-1538138398_

You understood me wrong. I dont want to parse an --argumentfile. I want that the user in vscode can just click run on a specific robot file and the listener will automaticly be called. I dont need an automated way for the console. When someone uses the console ro run robot files i dont want to silently append the custom listener but rather automaticly append it when you click debug or run in vscode (where you wont be prompted with console args)

**Comment by CasparQuast** [comment]
You understood me wrong. I dont want to parse an --argumentfile. I want that the user in vscode can just click run on a specific robot file and the listener will automaticly be called. I dont need an automated way for the console. When someone uses the console ro run robot files i dont want to silently append the custom listener but rather automaticly append it when you click debug or run in vscode (where you wont be prompted with console args)

**Comment by fabioz** [comment]
> You understood me wrong. I dont want to parse an --argumentfile. I want that the user in vscode can just click run on a specific robot file and the listener will automaticly be called. I dont need an automated way for the console. When someone uses the console ro run robot files i dont want to silently append the custom listener but rather automaticly append it when you click debug or run in vscode (where you wont be prompted with console args)

Exactly, that faq entry does exactly what you want, it'll automatically add any argument you specify -- if you craft your launch configuration as the faq says (with the name specified there) it should exactly what you're saying (if you name it as `Robot Framework: Launch template` it will automatically use it as a template when you do shortcut launches it'll add those arguments).

-- but instead of `["--argumentfile", "/path/to/arguments.txt"]` you probably want something as `["--listener", "path/to/listener.py"]`

p.s.: if you aren't t doing shortcut launches (i.e.: code-lenses) and are launching something regularly you should just add the proper arguments to your launch configuration (and then debug/run will use those arguments).

**Comment by CasparQuast** [comment]
Okay perfect. Thanks alot!
