### ISSUE TITLE
Calling custom listener with a specified class

### ISSUE THREAD

**Issue by CasparQuast** [robocorp/robotframework-lsp#930]
I have a custom listener (listener.py) with a class for the listener.
If i have the listener installed via python modules theres no problem to call the python file with the class --listener listener.ClassName
but if i just have a python file which isnt a module i cant access the class because only --listener listener.py is allowed. Is there any undocumented way of telling robot command line which class i want to use without having to install the listener to be available in the python modules list
![Unbenannt](https://github.com/robocorp/robotframework-lsp/assets/132852064/d684a6e1-e48d-47d5-bafb-9500e45695f5)

**Comment by fabioz** [comment]
You can provide the full path to the listener (maybe using the `${workspaceFolder}` variable: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-specify-a-variable-needed-to-resolve-some-library-or-resource-import) or you can fix your PYTHONPATH so that it can be found when specifying the name -- you can do this with the `robot.pythonpath` setting: https://github.com/robocorp/robotframework-lsp/blob/master/robotframework-ls/docs/faq.md#how-to-use-variables-in-settings.
