### ISSUE TITLE
Robot Framework Debugger is not working in Windows 11

### ISSUE THREAD

**Issue by prasuujju** [robocorp/robotframework-lsp#957]
Hi,

We upgraded from Windows 10 to Windows 11 and Robot framework code  Debugger is not working after that. Here are the versions we use .. anyone faced similar issue and any resolution is appreciated . Thank you. 

Python 3.10.11
Robot Framework language server - v1.11.0
robotframework                 6.0.2
pyreadline3                    3.4.1
robotframework-debuglibrary    2.3.0
robotframework-seleniumlibrary 6.1.0
selenium                       4.2.0

Here is the error information that we are facing 

[ ERROR ] Error in file Importing library //User/robot_scripts\TerminalDebugLibrary.py' failed: ModuleNotFoundError: No module named 'pyreadline'
File "C:\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 78, in until
    value = method(self._driver)
  File "C:\Python310\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 158, in _predicate
    return driver.find_elements(*locator)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 1284, in find_elements
    return self.execute(Command.FIND_ELEMENTS, {
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 430, in execute
    self.error_handler.check_response(response)
  File "C:\Python310\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 246, in check_response
    raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here
[ ERROR ] Calling method 'end_keyword' of listener 'C:\Users\User\.vscode\extensions\robot_scripts\FailListener.py' failed: No keyword with name 'Debug' found.

**Comment by cmin764** [comment]
Hi @prasuujju

If you're using our extension through VSCode, we recommend debugging the bot by running **Cmd/Ctrl+Shift+P** -> **Debug robot** and then a flow like this following your breakpoints will display:
<img width="750" alt="Screenshot 2023-07-20 at 18 50 37" src="https://github.com/robocorp/robotframework-lsp/assets/709053/07a7fc11-5e51-41dc-ac94-62c4c2d097d2">
<img width="1427" alt="Screenshot 2023-07-20 at 18 52 15" src="https://github.com/robocorp/robotframework-lsp/assets/709053/2c512f9a-55e6-40d5-a2ee-b33226b87058">

The `Debug` keyword is something maintained solely by Robot Framework (we're in charge of `rpaframework` library, which doesn't seem to be used according to the deps above), so it might be better to post this issue in the author's repo or on their Slack channel.
In order to debug it more, it looks like the environment couldn't be built (or some import is failing), therefore it lacks that `Debug` keyword, so watch out for the logs in case there's an importing error.

At the same time, we recommend you use our [tooling](https://robocorp.com/download) to manage the environments and build bots. I'll close this for now, but please re-open if you think this is a Robocorp / RPA Framework matter where we have control over.
