### ISSUE TITLE
Plugin is trying to download conda manager (rcc) forever

### ISSUE THREAD

**Issue by PretoPlasma** [robocorp/robotframework-lsp#974]
**Describe the bug**
After installing the Robocorp Code Plugin in vscode and Opening the Plugin the Sections for "Robots", "Robot Content", "Resources", "Robocorp" are empty. A progress line is displayed whilst the vscode pop up in the lower right corner shows "Download conda manager (rcc)" forever.

I spent my computer a couple of hours however there seems to be no progress...

**To Reproduce**
1. Open vscode
2. Search Robocorp Code Plugin in Plugins
3. Install Robocorp Code Plugin
4. Open / Create a robot project
5. After completion open Ropocorp Plugin

**Expected behavior**
I would expect that the Content Areas of the Robocorp Plugin show the content related to the opened / created robot.

**Screenshots**
![image](https://github.com/robocorp/robotframework-lsp/assets/107237119/2d74317b-6bf4-45e9-b6b4-4e7c81156f29)
![image](https://github.com/robocorp/robotframework-lsp/assets/107237119/9dcce137-0290-4f90-a024-ea01d14433bf)

**Versions:**
 - OS: Windows 10
 - Robocorp Code Version: 1.10.0 
 - Robot Framework Language Server Version: 1.11.0
 - Client Version: VSCode 1.81.1

**Comment by fabioz** [comment]
It's a 10MB file (rcc is required to create the virtual environments), so, it shouldn't take that long... 

Just restarting VSCode could work (if it was a one off) so that it redownloads.

If that doesn't work you can manually download it and put it in the proper place.

For that you can execute the VSCode command:

`Extensions: Open Extensions Folder`

![image](https://github.com/robocorp/robotframework-lsp/assets/117621/189fc84e-0b04-4039-bab2-712d44ce1d2a)

Then go to `robocorp.robocorp-code-1.10.0/bin` in that folder:

![image](https://github.com/robocorp/robotframework-lsp/assets/117621/813b65ca-e2fe-4f11-9296-5586b6cc28bf)

And download `rcc.exe` from https://downloads.robocorp.com/rcc/releases/v14.15.4/windows64/rcc.exe into that folder.

**Comment by PretoPlasma** [comment]
thanks @fabioz . that does the trick for me.
